### ISSUE TITLE
[FEATURE] Agendamento de Bloqueio

### ISSUE THREAD

**Issue by RobsonTrasel** [bet-blocker/bet-blocker#20]
Gostaria de sugerir a implementação de um **sistema de agendamento de bloqueio**. Essa funcionalidade permitiria aos usuários definir horários específicos em que os sites serão bloqueados automaticamente, oferecendo um controle mais granular e personalizado sobre o acesso a sites de apostas.

### Motivação:

- **Flexibilidade Personalizada**: Usuários podem ter diferentes períodos do dia em que se sentem mais vulneráveis ou distraídos. Permitir o agendamento ajuda a bloquear sites nos momentos mais críticos.
- **Produtividade**: Bloquear sites de apostas durante o horário de trabalho ou estudo pode ajudar a manter o foco e a produtividade.
- **Controle de Compulsão**: Para pessoas que lutam contra o jogo compulsivo, essa funcionalidade pode ser uma ferramenta adicional para ajudar a gerenciar o comportamento.

**Comment by braiansmarzaro** [comment]
Não acho que o intuito seja flexibilizar. Não existe momento bom para uma pessoa viciada acessar a bet.

**Comment by RobsonTrasel** [comment]
> Não acho que o intuito seja flexibilizar. Não existe momento bom para uma pessoa viciada acessar a bet.

Sim sim, pensando por esse lado fica mais claro mesmo.
